#networks:
#  1panel-network:
#    external: true
services:
  dw-admin:
    # 容器名称
    container_name: dw-admin
    # 镜像
    image: ghcr.io/dawei1898/dw-admin:latest
    # 端口映射 宿主机端口：容器内端口
    ports:
      - 8020:8020
    # 失败重启 尝试5次
    restart: on-failure:5
    # 挂载目录 宿主机目录：容器内目录
    volumes:
      - ./logs:/app/logs
    # 容器内工作目录
    working_dir: /app
    # 环境变量
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=dev