server:
  port: 8020

spring:
  application:
      name: dw-admin-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dwa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username:
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB

# mybatis-plus
mybatis-plus:
  mapperLocations: classpath:mapper/*.xml


# log??
logging:
  config: classpath:logback/logback-spring.xml
  level:
    com.dw.admin.dao: debug

dwa:
  auth:
    cache-type: DB
    secret: wq8wqh87a6f-8hslu9wedhsad-89dsaud8j-d6dy-dsja
  redis:
    url: localhost:6379
    password:
  # 文件存储配置
  storage:
    # 存储提供商: aliyun-oss (阿里云对象存储), tencent-cos (腾讯云对象存储)
    provider: aliyun-oss
    # 阿里云OSS配置
    aliyun-oss:
      access-key: xxxxxx
      secret-key: xxxxxx
      endpoint: xxxxxx.aliyuncs.com
      bucket-name: xxxxxx-oss-bucket
      prefix-path: xxxxxx/
      url-expires: 604800
    # 腾讯云COS配置
    tencent-cos:
      secret-id: xxxxxx
      secret-key: xxxxxx
      region: ap-beijing
      bucket-name: xxxxxx-1384986712
      prefix-path: xxxxxx/
      url-expires: 604800